name: bregzy_vendor
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_splash: ^1.0.0

  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.10.0
  http: ^0.12.2
  eva_icons_flutter: ^2.0.1
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  multi_image_picker: ^4.7.14
  http_parser: ^3.1.4
  awesome_dialog: ^1.2.1
  google_fonts: ^1.1.1
  auto_size_text: ^2.1.0
  cached_network_image: ^2.4.1
  pie_chart: ^4.0.1
  multiselect_formfield: ^0.1.5
  async: ^2.4.2
  smooth_star_rating: ^1.1.1
  flutter_absolute_path: ^1.0.6
  image_picker: ^0.6.7+17
  intl: ^0.16.1


  image: ^2.1.19












dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/



  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
   # - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
